apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: test-el
  namespace: pipelines-03682978
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: pipelines-03682978
