apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-task
  namespace: pipelines-03682978
spec:
  params:
  - name: git-repo-url
    type: string
  - name: git-repo-name
    type: string
  - name: git-revision
    type: string
  steps:
  - name: task-step
    image: image-registry.openshift-image-registry.svc:5000/openshift/ubi8-minimal:latest
    script: |
      echo "$(params.git-repo-url), $(params.git-repo-name), $(params.git-revision)"
