apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  labels:
    type: pipelines-03682978
  name: pipelines-03682978
  namespace: pipelines-03682978
spec:
  bindings:
  - ref: test-tb
  template:
    ref: test-tt
# The below part is optional and only useful when integrating with GitHub
  interceptors:
  - ref:
      kind: ClusterInterceptor
      name: github
